AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Access log trigger


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AccessLogTrigger:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./LambdaCode
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 900
      Role: 'arn:aws:iam::937333453566:role/CloudFormationServiceRole'
      Environment:
        Variables:
          REGION: eu-west-1